version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hcpromedical-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tl11fjs109n3"
s3_prefix = "hcpromedical-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
